### ISSUE TITLE
Error: Twit config must include `consumer_key` when using user auth.

### ISSUE THREAD

**Issue by vanucci** [gokatz/twigo#3]
Error: Twit config must include `consumer_key` when using user auth.

My config is setup correctly, had a google and cant find a reason for this or how to solve it.

**Comment by gokatz** [comment]
Are you using the latest version of twit? and it'll be helpful if you share your repository if any.

**Comment by gokatz** [comment]
@vanucci, Hope you solve the issue. Closing for now. Reopen if you need any help.
